### ISSUE TITLE
Problems installing this component

### ISSUE THREAD

**Issue by brucemacin** [miyako/4d-tips-virtual-user-mode#1]
Hello.  When I copy the VirtualUserMode.4dbase file into my Components folder and restart my v15 database, I only see the letter H in my Component Methods.  

When I click on this the right pane of the Explorer shows nothing.  Other Components I have installed show the Method on the right side pane.  Please let me know if I need to do something else to make this Component function.

**Comment by miyako** [comment]
H is a place holder **H**ost. the component is supposed to be installed in **H**

**Comment by miyako** [comment]
PICT icons are missing, _o_IMPORT ODBC is not implemented, but otherwise, the component runs up to v17 or v18. look for ``User Mode.4dbase`` inside ``VirtualUserMode.4dbase/Components/``

**Comment by brucemacin** [comment]
Thank you. But once the VirtualUserMode.4dbase is installed into the components folder, how do you call it from within the database to run it ?

Bruce Macin

**Comment by miyako** [comment]
again, "VirtualUserMode.4dbase" is a placeholder host, it is NOT the component to install. 

it only exists to illustrate how to invoke the component (see the menu item "USER MODE")

**Comment by brucemacin** [comment]
Thanks again for the info.  I showed package contents and copied over the User Mode.4dbase to my database and now I can view it in the explorer.   

Do you have any help files or instructions as to what I need to do now to my database to be able to use it?  I am a business owner and not a programmer and I wrote this software about 30 years ago in Version 1 of 4D and have updated along the way for y business as necessary.  As such I am not as knowledgeable in this as people you are used to dealing with.  I apologize but would appreciate any guidance you can provide as to what I need to do to get this to work for me (ie Create a Menu that calls specific methods etc.  I thank you in advance and stay healthy !!

(I am using the quarantine during this crisis to finally catch up on some programming that I have not had time to do in the past)

Thank you so much!
Bruce Macin
